# permissions for end users to edit managedjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: jobs-manager-operator
    app.kubernetes.io/part-of: jobs-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: managedjob-editor-role
rules:
- apiGroups:
  - jobsmanager.raczylo.com
  resources:
  - managedjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobsmanager.raczylo.com
  resources:
  - managedjobs/status
  verbs:
  - get
